### ISSUE TITLE
target branch null not found

### ISSUE THREAD

**Issue by duerrsimon** [mesh-iit/gh-action-repo-selective-sync#2]
I am trying to use this to sync a "teacher" and "student" version of a collection of markdown files. 

### publish.yml
```name: Publish Repo

on:
  push:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
    - uses: icub-tech-iit/gh-action-repo-selective-sync@v1.0.0
      with:
        recipe-file: '.publish/recipe.yml'
        token-source: ${{ secrets.GITHUB_TOKEN }}
        token-target: ${{ secrets.TARGET_PAT }}
```

I set TARGET_PAT to a personal access token for my account.

### recipe-file
```
source:
  copy_from:
    - "README.md"
    - ".gitignore"
    - "book"
target:
  repo: "duerrsimon/jb_clone_public"
  maxsize_commit_MB: 1000
  commit_message: "publish student version"
  copy_to:
    - "README.md"
    - ".gitignore"
    - "book"
  remove_after_copy:
    - "book/Exercises/*_instructor*"
   ```

The action does not run because it tries to clone a null branch. 
```
Synching target repo = "null"
source_branch = main
source_sha = 684f599b759fa385e3802f7a80e354935d1955f0
Cloning into '/home/runner/work/jb_clone_test/jb_clone_test/duerrsimon/jb_clone_test'...
HEAD is now at 684f599 update recipe
Target branch "null" detected; switching to fallback "main"
Cloning into '/home/runner/work/jb_clone_test/jb_clone_test/null'...
Using target branch = "main"
remote: Not Found
fatal: repository 'https://github.com/null.git/' not found
Error: Process completed with exit code 128.
```

Do you have a quick pointer on how to fix this?
